export const INSTRUMENT_CONFIG: Record<string, any> = {
  equity: {
    label: 'Equity',
    category: 'Equity & Exchange-traded',
    description: 'OTC block trade in NGX-listed shares',
    regulator: 'SEC Nigeria / NGX',
    metadata_fields: [],
    mandatory_docs: ['term_sheet', 'deed_of_assignment', 'aml_declaration'],
    warning_docs: ['board_resolution'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
  tbill: {
    label: 'Treasury Bill',
    category: 'Money Market',
    description: 'Secondary trade in FGN Treasury Bills',
    regulator: 'CBN / DMO',
    metadata_fields: [
      { key: 'face_value', label: 'Face value (₦)', type: 'number', required: true },
      { key: 'discount_rate', label: 'Discount rate (%)', type: 'number', required: true },
      { key: 'tenor_days', label: 'Tenor (days)', type: 'select', options: [91, 182, 364], required: true },
      { key: 'maturity_date', label: 'Maturity date', type: 'date', required: true },
      { key: 'series', label: 'Series/issuance reference', type: 'text', required: false },
    ],
    mandatory_docs: ['agreement', 'aml_declaration'],
    warning_docs: ['source_of_funds'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
  bond: {
    label: 'Bond',
    category: 'Fixed Income',
    description: 'Secondary trade in FGN or corporate bonds',
    regulator: 'SEC Nigeria / DMO',
    metadata_fields: [
      { key: 'bond_name', label: 'Bond name/series', type: 'text', required: true },
      { key: 'issuer', label: 'Issuer', type: 'text', required: true },
      { key: 'face_value', label: 'Face value (₦)', type: 'number', required: true },
      { key: 'coupon_rate', label: 'Coupon rate (% p.a.)', type: 'number', required: true },
      { key: 'maturity_date', label: 'Maturity date', type: 'date', required: true },
      { key: 'agreed_price', label: 'Agreed trade price (₦)', type: 'number', required: true },
      { key: 'yield_to_maturity', label: 'Yield to maturity (%)', type: 'number', required: false },
      { key: 'accrued_interest', label: 'Accrued interest (₦)', type: 'number', required: false },
    ],
    mandatory_docs: ['agreement', 'aml_declaration'],
    warning_docs: ['source_of_funds', 'beneficial_ownership'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
  commercial_paper: {
    label: 'Commercial Paper',
    category: 'Money Market',
    description: 'Short-term unsecured promissory note, 30–270 days tenor',
    regulator: 'SEC Nigeria / FMDQ / CBN',
    metadata_fields: [
      { key: 'issuer_name', label: 'Issuer name', type: 'text', required: true },
      { key: 'issuer_rc_number', label: 'Issuer RC number', type: 'text', required: true },
      { key: 'face_value', label: 'Face value (₦)', type: 'number', required: true },
      { key: 'discount_rate', label: 'Discount rate (%)', type: 'number', required: true },
      { key: 'tenor_days', label: 'Tenor (days)', type: 'select', options: [30, 60, 90, 180, 270], required: true },
      { key: 'issue_date', label: 'Issue date', type: 'date', required: true },
      { key: 'maturity_date', label: 'Maturity date', type: 'date', required: true },
      { key: 'credit_rating', label: 'Credit rating (Agusto/GCR/S&P)', type: 'text', required: false },
      { key: 'credit_rating_agency', label: 'Rating agency', type: 'select', options: ['Agusto & Co', 'GCR Ratings', 'S&P', 'Fitch', 'Unrated'], required: false },
      { key: 'dealer_arranger', label: 'Dealer/Arranger', type: 'text', required: true },
      { key: 'issuing_paying_agent', label: 'Issuing and paying agent (bank)', type: 'text', required: true },
      { key: 'min_subscription', label: 'Minimum subscription (₦)', type: 'number', required: true },
      { key: 'programme_size', label: 'Programme size (₦)', type: 'number', required: false },
      { key: 'fmdq_registration', label: 'FMDQ registration number', type: 'text', required: false },
      { key: 'series_number', label: 'Series/tranche number', type: 'text', required: false },
    ],
    mandatory_docs: ['information_memorandum', 'credit_rating', 'dealer_agreement', 'aml_declaration'],
    warning_docs: ['programme_memorandum', 'beneficial_ownership'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
  bankers_acceptance: {
    label: "Banker's Acceptance",
    category: 'Money Market',
    description: 'Bank-guaranteed short-term instrument, typically 30–180 days',
    regulator: 'CBN',
    metadata_fields: [
      { key: 'accepting_bank', label: 'Accepting bank', type: 'text', required: true },
      { key: 'drawee', label: 'Drawee (original issuer)', type: 'text', required: true },
      { key: 'face_value', label: 'Face value (₦)', type: 'number', required: true },
      { key: 'discount_rate', label: 'Discount rate (%)', type: 'number', required: true },
      { key: 'tenor_days', label: 'Tenor (days)', type: 'select', options: [30, 60, 90, 120, 180], required: true },
      { key: 'issue_date', label: 'Issue date', type: 'date', required: true },
      { key: 'maturity_date', label: 'Maturity date', type: 'date', required: true },
      { key: 'underlying_trade', label: 'Underlying trade description', type: 'text', required: false },
    ],
    mandatory_docs: ['agreement', 'aml_declaration'],
    warning_docs: ['source_of_funds'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
  promissory_note: {
    label: 'Promissory Note',
    category: 'Money Market',
    description: 'Corporate promise to pay a specified amount at a future date',
    regulator: 'SEC Nigeria',
    metadata_fields: [
      { key: 'maker_name', label: 'Maker (issuer) name', type: 'text', required: true },
      { key: 'maker_rc_number', label: 'Maker RC number', type: 'text', required: true },
      { key: 'payee_name', label: 'Payee name', type: 'text', required: true },
      { key: 'principal_amount', label: 'Principal amount (₦)', type: 'number', required: true },
      { key: 'interest_rate', label: 'Interest rate (% p.a.)', type: 'number', required: false },
      { key: 'issue_date', label: 'Issue date', type: 'date', required: true },
      { key: 'maturity_date', label: 'Maturity date', type: 'date', required: true },
      { key: 'payment_terms', label: 'Payment terms', type: 'select', options: ['Lump sum at maturity', 'Monthly instalments', 'Quarterly instalments'], required: true },
      { key: 'security', label: 'Security/collateral (if any)', type: 'text', required: false },
    ],
    mandatory_docs: ['agreement', 'aml_declaration'],
    warning_docs: ['source_of_funds', 'board_resolution'],
    escrow_hard_block_types: ['institutional'],
  },
  reit_units: {
    label: 'REIT Units',
    category: 'Equity & Exchange-traded',
    description: 'Secondary trade in Real Estate Investment Trust units',
    regulator: 'SEC Nigeria',
    metadata_fields: [
      { key: 'reit_name', label: 'REIT name', type: 'text', required: true },
      { key: 'reit_ticker', label: 'REIT ticker (if listed)', type: 'text', required: false },
      { key: 'unit_count', label: 'Number of units', type: 'number', required: true },
      { key: 'nav_per_unit', label: 'NAV per unit (₦)', type: 'number', required: false },
      { key: 'agreed_price_per_unit', label: 'Agreed price per unit (₦)', type: 'number', required: true },
      { key: 'distribution_rights', label: 'Distribution rights transfer', type: 'select', options: ['Full transfer', 'Seller retains current period', 'Buyer gets current period'], required: true },
    ],
    mandatory_docs: ['deed_of_assignment', 'aml_declaration'],
    warning_docs: ['beneficial_ownership'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
  eurobond: {
    label: 'Eurobond (Secondary)',
    category: 'Fixed Income',
    description: 'Secondary market trade in Nigerian corporate or FGN Eurobonds',
    regulator: 'SEC Nigeria / CBN',
    metadata_fields: [
      { key: 'bond_name', label: 'Bond name/ISIN', type: 'text', required: true },
      { key: 'issuer', label: 'Original issuer', type: 'text', required: true },
      { key: 'currency', label: 'Currency', type: 'select', options: ['USD', 'EUR', 'GBP'], required: true },
      { key: 'face_value', label: 'Face value', type: 'number', required: true },
      { key: 'coupon_rate', label: 'Coupon rate (% p.a.)', type: 'number', required: true },
      { key: 'maturity_date', label: 'Maturity date', type: 'date', required: true },
      { key: 'agreed_price', label: 'Agreed trade price (% of par)', type: 'number', required: true },
      { key: 'yield_to_maturity', label: 'Yield to maturity (%)', type: 'number', required: false },
      { key: 'accrued_interest', label: 'Accrued interest', type: 'number', required: false },
      { key: 'settlement_currency', label: 'Settlement currency', type: 'select', options: ['USD', 'NGN'], required: true },
    ],
    mandatory_docs: ['agreement', 'aml_declaration', 'source_of_funds'],
    warning_docs: ['beneficial_ownership', 'pep_declaration'],
    escrow_hard_block_types: ['institutional', 'corporate', 'qualified'],
  },
  rights_nil_paid: {
    label: 'Rights Issue Nil-Paid Letters',
    category: 'Equity & Exchange-traded',
    description: 'Transfer of unexercised rights entitlements during a rights issue',
    regulator: 'SEC Nigeria / NGX',
    metadata_fields: [
      { key: 'company_name', label: 'Issuing company', type: 'text', required: true },
      { key: 'company_ticker', label: 'NGX ticker', type: 'text', required: true },
      { key: 'rights_ratio', label: 'Rights ratio (e.g. 1 for 4)', type: 'text', required: true },
      { key: 'subscription_price', label: 'Subscription price (₦)', type: 'number', required: true },
      { key: 'number_of_rights', label: 'Number of rights being sold', type: 'number', required: true },
      { key: 'rights_expiry_date', label: 'Rights expiry date', type: 'date', required: true },
      { key: 'seller_cscs_account', label: "Seller's CSCS account number", type: 'text', required: true },
    ],
    mandatory_docs: ['deed_of_assignment', 'agreement'],
    warning_docs: ['aml_declaration'],
    escrow_hard_block_types: ['institutional'],
  },
  agri_commodity_forward: {
    label: 'Agricultural Commodity Forward',
    category: 'Other',
    description: 'Forward contract for delivery of agricultural commodities',
    regulator: 'SEC Nigeria',
    metadata_fields: [
      { key: 'commodity_type', label: 'Commodity', type: 'select', options: ['Cocoa', 'Sesame', 'Cashew', 'Maize', 'Sorghum', 'Palm Oil', 'Groundnut', 'Cassava', 'Cotton', 'Other'], required: true },
      { key: 'quantity_tonnes', label: 'Quantity (metric tonnes)', type: 'number', required: true },
      { key: 'quality_grade', label: 'Quality grade/specification', type: 'text', required: true },
      { key: 'agreed_price_per_tonne', label: 'Agreed price per tonne (₦)', type: 'number', required: true },
      { key: 'delivery_date', label: 'Delivery date', type: 'date', required: true },
      { key: 'delivery_location', label: 'Delivery location/warehouse', type: 'text', required: true },
      { key: 'quality_inspection', label: 'Quality inspection agent', type: 'text', required: false },
      { key: 'advance_payment_pct', label: 'Advance payment (%)', type: 'number', required: false },
    ],
    mandatory_docs: ['agreement', 'aml_declaration'],
    warning_docs: ['source_of_funds'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
  sukuk: {
    label: 'Sukuk (Secondary)',
    category: 'Fixed Income',
    description: "Secondary trade in Shari'ah-compliant bond instruments",
    regulator: 'SEC Nigeria / CBN',
    metadata_fields: [
      { key: 'sukuk_name', label: 'Sukuk name/series', type: 'text', required: true },
      { key: 'issuer', label: 'Issuer', type: 'text', required: true },
      { key: 'structure_type', label: 'Sukuk structure', type: 'select', options: ['Ijarah', 'Murabaha', 'Musharakah', 'Wakalah', 'Mudarabah'], required: true },
      { key: 'face_value', label: 'Face value (₦)', type: 'number', required: true },
      { key: 'profit_rate', label: 'Profit rate (% p.a.)', type: 'number', required: true },
      { key: 'maturity_date', label: 'Maturity date', type: 'date', required: true },
      { key: 'agreed_price', label: 'Agreed trade price (₦)', type: 'number', required: true },
      { key: 'shariah_advisor', label: "Shari'ah advisor", type: 'text', required: false },
    ],
    mandatory_docs: ['agreement', 'aml_declaration'],
    warning_docs: ['beneficial_ownership'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
  infrastructure_bond: {
    label: 'Infrastructure Bond',
    category: 'Fixed Income',
    description: 'Long-dated bond issued for specific infrastructure projects',
    regulator: 'SEC Nigeria / DMO',
    metadata_fields: [
      { key: 'bond_name', label: 'Bond name/series', type: 'text', required: true },
      { key: 'issuer', label: 'Issuer', type: 'text', required: true },
      { key: 'project_description', label: 'Underlying project', type: 'text', required: true },
      { key: 'face_value', label: 'Face value (₦)', type: 'number', required: true },
      { key: 'coupon_rate', label: 'Coupon rate (% p.a.)', type: 'number', required: true },
      { key: 'maturity_date', label: 'Maturity date', type: 'date', required: true },
      { key: 'agreed_price', label: 'Agreed trade price (₦)', type: 'number', required: true },
      { key: 'credit_enhancement', label: 'Credit enhancement (if any)', type: 'text', required: false },
      { key: 'tax_exempt', label: 'Tax exempt status', type: 'select', options: ['Yes - tax exempt', 'No - taxable'], required: true },
    ],
    mandatory_docs: ['agreement', 'aml_declaration', 'source_of_funds'],
    warning_docs: ['beneficial_ownership', 'pep_declaration'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
  esos: {
    label: 'Employee Share Options (ESOS)',
    category: 'Equity & Exchange-traded',
    description: 'Transfer of vested employee share options before company listing',
    regulator: 'SEC Nigeria',
    metadata_fields: [
      { key: 'company_name', label: 'Company name', type: 'text', required: true },
      { key: 'option_scheme_name', label: 'Option scheme name', type: 'text', required: true },
      { key: 'number_of_options', label: 'Number of options', type: 'number', required: true },
      { key: 'exercise_price', label: 'Exercise price per share (₦)', type: 'number', required: true },
      { key: 'agreed_transfer_price', label: 'Agreed transfer price per option (₦)', type: 'number', required: true },
      { key: 'vesting_date', label: 'Vesting date', type: 'date', required: true },
      { key: 'expiry_date', label: 'Option expiry date', type: 'date', required: true },
      { key: 'company_consent', label: 'Company consent to transfer', type: 'select', options: ['Obtained', 'Pending', 'Not required'], required: true },
      { key: 'lock_up_restrictions', label: 'Lock-up/transfer restrictions', type: 'text', required: false },
    ],
    mandatory_docs: ['agreement', 'deed_of_assignment', 'board_resolution'],
    warning_docs: ['aml_declaration'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
  private_placement: {
    label: 'Private Placement',
    category: 'Other',
    description: 'Securities offered to select qualified investors',
    regulator: 'SEC Nigeria',
    metadata_fields: [
      { key: 'issuer_name', label: 'Issuer name', type: 'text', required: true },
      { key: 'security_type', label: 'Security type', type: 'select', options: ['Ordinary shares', 'Preference shares', 'Convertible notes', 'Hybrid'], required: true },
      { key: 'number_of_units', label: 'Number of units offered', type: 'number', required: true },
      { key: 'price_per_unit', label: 'Price per unit (₦)', type: 'number', required: true },
      { key: 'min_subscription', label: 'Minimum subscription (₦)', type: 'number', required: true },
      { key: 'use_of_proceeds', label: 'Use of proceeds', type: 'text', required: true },
      { key: 'offer_open_date', label: 'Offer open date', type: 'date', required: true },
      { key: 'offer_close_date', label: 'Offer close date', type: 'date', required: true },
    ],
    mandatory_docs: ['information_memorandum', 'subscription_agreement', 'aml_declaration', 'board_resolution'],
    warning_docs: ['beneficial_ownership', 'pep_declaration', 'source_of_funds'],
    escrow_hard_block_types: ['institutional', 'corporate', 'qualified'],
  },
  off_market: {
    label: 'Off-Market Trade',
    category: 'Other',
    description: 'Negotiated trade outside normal exchange mechanisms',
    regulator: 'SEC Nigeria / NGX',
    metadata_fields: [],
    mandatory_docs: ['agreement', 'aml_declaration'],
    warning_docs: ['source_of_funds'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
  fixed_income: {
    label: 'Fixed Income (General)',
    category: 'Fixed Income',
    description: 'General fixed income instrument not covered by other categories',
    regulator: 'SEC Nigeria',
    metadata_fields: [
      { key: 'instrument_description', label: 'Instrument description', type: 'text', required: true },
      { key: 'face_value', label: 'Face value (₦)', type: 'number', required: true },
      { key: 'return_rate', label: 'Return rate (% p.a.)', type: 'number', required: true },
      { key: 'maturity_date', label: 'Maturity date', type: 'date', required: true },
    ],
    mandatory_docs: ['agreement', 'aml_declaration'],
    warning_docs: ['source_of_funds'],
    escrow_hard_block_types: ['institutional', 'corporate'],
  },
};

export const DOC_LABELS: Record<string, { label: string; description: string }> = {
  term_sheet: { label: 'Term Sheet', description: 'Signed term sheet agreed by all parties' },
  agreement: { label: 'Transaction Agreement', description: 'Full executed transaction agreement' },
  letter_of_offer: { label: 'Letter of Offer', description: 'Formal offer letter from seller to buyer' },
  subscription_agreement: { label: 'Subscription Agreement', description: 'Investor commitment and subscription terms' },
  deed_of_assignment: { label: 'Deed of Assignment', description: 'Legal transfer of ownership document' },
  comfort_letter: { label: 'Comfort Letter', description: 'Bank confirmation of fund availability' },
  information_memorandum: { label: 'Information Memorandum', description: 'Full disclosure document for the instrument' },
  programme_memorandum: { label: 'Programme Memorandum', description: 'Programme-level disclosure for series issuances' },
  dealer_agreement: { label: 'Dealer Agreement', description: 'Agreement between issuer and authorised dealer' },
  credit_rating: { label: 'Credit Rating Certificate', description: 'Current credit rating from Agusto, GCR, or S&P' },
  regulatory_filing: { label: 'SEC/FMDQ Filing Confirmation', description: 'Confirmation of regulatory registration' },
  board_resolution: { label: 'Board Resolution', description: 'Board authorisation for transaction participation' },
  aml_declaration: { label: 'AML/CFT Declaration', description: 'Anti-money laundering declaration' },
  source_of_funds: { label: 'Source of Funds Declaration', description: 'CBN-required declaration of funds origin' },
  pep_declaration: { label: 'PEP Declaration', description: 'Politically Exposed Persons self-certification' },
  beneficial_ownership: { label: 'Beneficial Ownership Disclosure', description: 'CBN-mandated beneficial ownership declaration' },
  cscs_instruction: { label: 'CSCS Transfer Instruction', description: 'Central Securities Clearing System transfer form' },
  id_document: { label: 'Identity Document', description: 'Government-issued ID' },
  other: { label: 'Other Document', description: 'Supporting documentation' },
};

export function getChecklist(deal_type: string, account_type: string) {
  const config = INSTRUMENT_CONFIG[deal_type];
  if (!config) return { mandatory: [], recommended: [], hard_block_escrow: false };
  return {
    mandatory: config.mandatory_docs.map((d: string) => ({ doc_type: d, ...DOC_LABELS[d] })),
    recommended: config.warning_docs.map((d: string) => ({ doc_type: d, ...DOC_LABELS[d] })),
    hard_block_escrow: config.escrow_hard_block_types.includes(account_type),
  };
}

export function getInstrumentLabel(deal_type: string): string {
  return INSTRUMENT_CONFIG[deal_type]?.label ?? deal_type;
}

export function getInstrumentCategory(deal_type: string): string {
  return INSTRUMENT_CONFIG[deal_type]?.category ?? 'Other';
}
